version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ADV_HOST=kafka
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    ports:
      - "9200:9200"

  kibana:
    image: docker.io/bitnami/kibana:7
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch

  logstash:
    image: docker.io/bitnami/logstash:7
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - ./logstash_kafka_input.conf:/bitnami/logstash/config/logstash_kafka_input.conf
    environment:
      - LOGSTASH_CONF_FILENAME=logstash_kafka_input.conf

  osrm-train:
    command:
      - osrm-routed
      - --algorithm
      - mld
      - /data522/output/filtered.osrm
    image: osrm/osrm-backend:v5.22.0
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    volumes:
      - ./:/data522